---
- name: Install openjdk and elasticsearch
  yum:
    name: "{{item}}"
    state: latest
  with_items:
    - java-1.8.0-openjdk
    - elasticsearch

- name: Configure elasticsearch
  template:
    src: elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
    owner: root
    group: elasticsearch
  notify: restart elasticsearch

- name: Setup custom ulimits
  template:
    src: security_limits.conf.j2
    dest: /etc/security/limits.d/elasticsearch-nproc.conf
    owner: root
    group: root

- name: Enable elasticsearch
  service:
    name: elasticsearch
    enabled: yes

- name: Start elasticsearch
  service:
    name: elasticsearch
    state: started
