---
- name: Install openjdk and logstash
  yum:
    name: "{{item}}"
    state: latest
  with_items:
    - java-1.8.0-openjdk
    - logstash

- name: Enable logstash
  service:
    name: logstash
    enabled: yes

- name: Start logstash
  service:
    name: logstash
    state: started
